version: '3.8'

services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        target: '/usr/src/app/node_modules'
      - type: bind
        source: ./backend/src
        target: '/usr/src/app/src'
    env_file:
      - ./backend/env/.env
    depends_on:
      - mongodb
  mongodb: 
    image: mongo
    volumes:
      - db_mongo:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./backend/env/mongo.env
volumes:
  db_mongo:
    