version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000-3010:3000"
    volumes:
      - type: volume
        target: '/usr/src/app/node_modules'
      - type: bind
        source: ./src
        target: '/usr/src/app/src'
    env_file:
      - ./env/.env
    depends_on:
      - mongodb
  mongodb: 
    image: mongo
    volumes:
      - db_mongo:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./env/mongo.env
volumes:
  db_mongo:
    